# Generated by Django 5.1.1 on 2024-11-13 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opencv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cardEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventText', models.CharField(max_length=500)),
                ('eventImage', models.ImageField(upload_to='events/')),
            ],
        ),
    ]
