# Generated by Django 5.1.3 on 2024-11-14 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opencv', '0002_cardevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='userInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=200, unique=True)),
                ('userAbout', models.CharField(max_length=500)),
                ('userImage', models.ImageField(upload_to='user_images/')),
            ],
        ),
    ]
